#!/bin/bash

if [ -f "/usr/local/bin/RemoteUpdateManager" ]; then
	VERSION=$(/usr/local/bin/RemoteUpdateManager --help 2>&1 | awk ' NR==1{ print $5 } ')
	echo "<result>$VERSION</result>"
else
    echo "<result>Not Installed</result>"
fi

exit 0
