#!/bin/bash

if [ -f "/usr/local/bin/RemoteUpdateManager" ]; then
	result=$(/usr/local/bin/RemoteUpdateManager --help 2>&1 | awk ' NR==1{ print $5 } ')
	echo "<result>$result</result>"
else
    echo "<result>Not Installed</result>"
fi

exit 0
