#!/bin/bash

# EA to determine the last xprotect update up through macOS Monterey
# this version will not work on Ventura - move to old EA repo

# https://github.com/franton/Extension-Attributes/blob/master/xprotectupdate.sh

date=$( ls -lT /System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/XProtect.meta.plist | awk '{ print $6,$7,$8,$9 }' )

# format=$( date -j -f "%d %b %H:%M:%S %Y" "$date" +"%Y-%m-%d %T" )
format=$( date -j "$date" +"%Y-%m-%d %H:%M:%S" )

echo $date
echo $format
